var message = [
    "Welcome to Geektopia",
    "Your nerdly travels begin here",
    "Are you ready for geekdom?",
    "I'm gonna make you an offer you can't refuse...",
    "Fasten your seatbelts. It's going to be a geeky ride!",
    "Made it, Ma! Top of the world!",
    "I think this is the beginning of a beautiful acquaintanceship.",
    "There's no place like EarthBound",
    "I'll show you how deep the rabbit hole goes",
    "I see smart people",
    "You had me at Encapsulation",
    "Geek, for lack of a better word, is good.",
    "Who's on first?",
    "You got the juice now, man",
    "Get over here!",
    "The right geek in the wrong place can make all the difference in the world",
    "It’s dangerous to go alone, take this!",
    "Endure and survive",
    "You are here, and it’s beautiful",
    'Thank you! But your princess is in another castle!',
    "Are you a boy or a girl?",
    "Wouldst thou like to live deliciously?",
    "Would that it were so simple",
    "Here at geeKeef, we all pee the same color",
    "The Force is with you. You are one with the Force",
    "I saw you make a spinach dip in a loaf of sourdough bread once",
    "Are you not entertained! Is this not why you are here!",
    "Donkey Kong aint got s--t on you!",
    "My precious...",
    "Of all the joints in all the webs in all the world, you walk into mine",
    "Just when I thought I was out, they pull me back in",
    "Do you know what they call a Quarter Pounder with cheese in Paris?",
    "01001000 01100101 01101100 01101100 01101111",
    "01010111 01100101 01101100 01100011 01101111 01101101 01100101",
    "To Infinity and Beyond!",
    "Do you like scary movies?",
    "Excuse me, yeah, uh, I believe you have my stapler...",
    "I sense much geek in you",
    "Only a jackass can change the world",
    "You were almost a nerd sandwich",
    "It's so geeky in here",
    "I know kung-fu"
]

module.exports = message;